package config

type Config struct {
	Url                                string `json:"url"`
	Broker                             string `json:"broker"`
	TopicAccesoAppMovil                string `json:"topicAccesoAppMovil"`
	TopicAccesoAppMovilPermisos        string `json:"topicAccesoAppMovilPermisos"`
	TopicAclaracionBl                  string `json:"topicAclaracionBl"`
	TopicAforosBlTr                    string `json:"topicAforosBlTr"`
	TopicAgenteAduana                  string `json:"topicAgenteAduana"`
	TopicAuxiliarAga                   string `json:"topicAuxiliarAga"`
	TopicBanco                         string `json:"topicBanco"`
	TopicBl                            string `json:"topicBl"`
	TopicBlFecha                       string `json:"topicBlFecha"`
	TopicBlFlete                       string `json:"topicBlFlete"`
	TopicBlImoContenedorAux            string `json:"topicBlImoContenedorAux"`
	TopicBlItem                        string `json:"topicBlItem"`
	TopicBlItemContenedor              string `json:"topicBlItemContenedor"`
	TopicBlItemContenedorImo           string `json:"topicBlItemContenedorImo"`
	TopicBlItemContenedorSello         string `json:"topicBlItemContenedorSello"`
	TopicBlItemImo                     string `json:"topicBlItemImo"`
	TopicBlItemTipoBulto               string `json:"topicBlItemTipoBulto"`
	TopicBlLocacion                    string `json:"topicBlLocacion"`
	TopicBlObservacion                 string `json:"topicBlObservacion"`
	TopicBlParticipante                string `json:"topicBlParticipante"`
	TopicBlProgramacionFaena           string `json:"topicBlProgramacionFaena"`
	TopicBlProgramacionFaenaFcl        string `json:"topicBlProgramacionFaenaFcl"`
	TopicBlProgramacionVa              string `json:"topicBlProgramacionVa"`
	TopicBlReferencia                  string `json:"topicBlReferencia"`
	TopicBlTransbordo                  string `json:"topicBlTransbordo"`
	TopicBlTransporte                  string `json:"topicBlTransporte"`
	TopicBultosTarjados                string `json:"topicBultosTarjados"`
	TopicCheque                        string `json:"topicCheque"`
	TopicChoferes                      string `json:"topicChoferes"`
	TopicClientes                      string `json:"topicClientes"`
	TopicContenedores                  string `json:"topicContenedores"`
	TopicContenedoresGuia              string `json:"topicContenedoresGuia"`
	TopicDespacho                      string `json:"topicDespacho"`
	TopicDespachoRemoto                string `json:"topicDespachoRemoto"`
	TopicDetalleFactura                string `json:"topicDetalleFactura"`
	TopicDireccionClte                 string `json:"topicDireccionClte"`
	TopicDireccionEmp                  string `json:"topicDireccionEmp"`
	TopicDocumento                     string `json:"topicDocumento"`
	TopicEdiBitacora                   string `json:"topicEdiBitacora"`
	TopicEmpresa                       string `json:"topicEmpresa"`
	TopicExpoDocumento                 string `json:"topicExpoDocumento"`
	TopicExpoIngresoBodega             string `json:"topicExpoIngresoBodega"`
	TopicExpoIngresoBodegaDetalle      string `json:"topicExpoIngresoBodegaDetalle"`
	TopicExpoIngresoBodegaFotos        string `json:"topicExpoIngresoBodegaFotos"`
	TopicExpoIngresoBodegaUbicacion    string `json:"topicExpoIngresoBodegaUbicacion"`
	TopicExpoPrestaking                string `json:"topicExpoPrestaking"`
	TopicExpoPrestakingFotos           string `json:"topicExpoPrestakingFotos"`
	TopicExpoProgCargaContenedor       string `json:"topicExpoProgCargaContenedor"`
	TopicExpoProgConsolidado           string `json:"topicExpoProgConsolidado"`
	TopicExpoProgConsolidadoContenedor string `json:"topicExpoProgConsolidadoContenedor"`
	TopicExpoProgConsolidadoDetalle    string `json:"topicExpoProgConsolidadoDetalle"`
	TopicExpoProgRevisionContenedor    string `json:"topicExpoProgRevisionContenedor"`
	TopicExpoRecepcion                 string `json:"topicExpoRecepcion"`
	TopicExpoRecepcionDetalle          string `json:"topicExpoRecepcionDetalle"`
	TopicExpoRecepcionFoto             string `json:"topicExpoRecepcionFoto"`
	TopicExpoRecepcionMedidasCajas     string `json:"topicExpoRecepcionMedidasCajas"`
	TopicExpoSalidaBodega              string `json:"topicExpoSalidaBodega"`
	TopicExpoSalidaBodegaFotos         string `json:"topicExpoSalidaBodegaFotos"`
	TopicFactura                       string `json:"topicFactura"`
	TopicFaltasYSobras                 string `json:"topicFaltasYSobras"`
	TopicFaltasYSobrasSinPapeleta      string `json:"topicFaltasYSobrasSinPapeleta"`
	TopicFolio                         string `json:"topicFolio"`
	TopicFonoEmp                       string `json:"topicFonoEmp"`
	TopicGlosaFactura                  string `json:"topicGlosaFactura"`
	TopicGuardaAlmacen                 string `json:"topicGuardaAlmacen"`
	TopicGuiaBultos                    string `json:"topicGuiaBultos"`
	TopicGuiaDespacho                  string `json:"topicGuiaDespacho"`
	TopicHermesEvento                  string `json:"topicHermesEvento"`
	TopicHistorialFolio                string `json:"topicHistorialFolio"`
	TopicHistorialIndicadores          string `json:"topicHistorialIndicadores"`
	TopicHorariosEmpresa               string `json:"topicHorariosEmpresa"`
	TopicIngresoTerminalExpo           string `json:"topicIngresoTerminalExpo"`
	TopicIngresoTerminalExpoDetalle    string `json:"topicIngresoTerminalExpoDetalle"`
	TopicIngresoTerminalFotos          string `json:"topicIngresoTerminalFotos"`
	TopicIngresoTerminales             string `json:"topicIngresoTerminales"`
	TopicInspeccionesPapeleta          string `json:"topicInspeccionesPapeleta"`
	TopicManifiesto                    string `json:"topicManifiesto"`
	TopicMercanciasDespachadas         string `json:"topicMercanciasDespachadas"`
	TopicMercanciasDespachadasVa       string `json:"topicMercanciasDespachadasVa"`
	TopicModPapeleta                   string `json:"topicModPapeleta"`
	TopicModVisacionVa                 string `json:"topicModVisacionVa"`
	TopicMotivoRebajaRecaudacion       string `json:"topicMotivoRebajaRecaudacion"`
	TopicNave                          string `json:"topicNave"`
	TopicNavieras                      string `json:"topicNavieras"`
	TopicNotaCredito                   string `json:"topicNotaCredito"`
	TopicNotaCreditoServ               string `json:"topicNotaCreditoServ"`
	TopicOperadoresEdi                 string `json:"topicOperadoresEdi"`
	TopicOrdenCompra                   string `json:"topicOrdenCompra"`
	TopicPalabraClave                  string `json:"topicPalabraClave"`
	TopicPapeletaRecepcion             string `json:"topicPapeletaRecepcion"`
	TopicPapeletaRecepcionDetalle      string `json:"topicPapeletaRecepcionDetalle"`
	TopicPapeletaRecepcionExpo         string `json:"topicPapeletaRecepcionExpo"`
	TopicPapeletaRecepcionExpoDetalle  string `json:"topicPapeletaRecepcionExpoDetalle"`
	TopicPrePapeleta                   string `json:"topicPrePapeleta"`
	TopicPrePapeletaVa                 string `json:"topicPrePapeletaVa"`
	TopicProvidencia                   string `json:"topicProvidencia"`
	TopicProvidenciaExportacion        string `json:"topicProvidenciaExportacion"`
	TopicPuertos                       string `json:"topicPuertos"`
	TopicRangoHorariosInscripcionInd   string `json:"topicRangoHorariosInscripcionInd"`
	TopicRegistroEdi                   string `json:"topicRegistroEdi"`
	TopicRegistroFolios                string `json:"topicRegistroFolios"`
	TopicRelAgaAux                     string `json:"topicRelAgaAux"`
	TopicRelFacturaMedioPago           string `json:"topicRelFacturaMedioPago"`
	TopicRelServiciosPapeleta          string `json:"topicRelServiciosPapeleta"`
	TopicRetencionesPapeleta           string `json:"topicRetencionesPapeleta"`
	TopicRetiroDirectoFcl              string `json:"topicRetiroDirectoFcl"`
	TopicRetiroDirectoFclDet           string `json:"topicRetiroDirectoFclDet"`
	TopicRetiroDirectoLcl              string `json:"topicRetiroDirectoLcl"`
	TopicRetiroIndirectoPiso           string `json:"topicRetiroIndirectoPiso"`
	TopicServicios                     string `json:"topicServicios"`
	TopicServiciosEliminados           string `json:"topicServiciosEliminados"`
	TopicTarifas                       string `json:"topicTarifas"`
	TopicTransferencia                 string `json:"topicTransferencia"`
	TopicTransporte                    string `json:"topicTransporte"`
	TopicTraspasoFacturacion           string `json:"topicTraspasoFacturacion"`
	TopicUbicacion                     string `json:"topicUbicacion"`
	TopicUsuarioAep                    string `json:"topicUsuarioAep"`
	TopicUsuarioAepPermisos            string `json:"topicUsuarioAepPermisos"`
	TopicUsuarioExterno                string `json:"topicUsuarioExterno"`
	TopicVisacion                      string `json:"topicVisacion"`
	TopicVisacionImo                   string `json:"topicVisacionImo"`
	TopicVisacionVa                    string `json:"topicVisacionVa"`
	TopicWsAnulacionTatc               string `json:"topicWsAnulacionTatc"`
	TopicWsLiberacionTatc              string `json:"topicWsLiberacionTatc"`
	TopicWsModificacionTatc            string `json:"topicWsModificacionTatc"`
	TopicZona                          string `json:"topicZona"`
}
