version: "3.9"

services:
  # Entorno de desarrollo
  api-auditoria-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: api-auditoria-dev
    restart: unless-stopped
    volumes:
      - .:/app
    working_dir: /app
    command: go run main.go
    ports:
      - "8181:8181"

